### PR TITLE
Fix crash when flag is captured while having active flag workers and enhance connect fail message for version mismatch

### LINKED ISSUE #1449: s25client crashing: pure virtual method called
Hello! 

Not sure how do I report the issue properly, terribly sorry.
I am running the latest s25client.exe build on Windows 10.
The game is crashing, and all I see in the console log is this message:

>pure virtual method called
>terminate called without an active exception

The log file has no messages related to the crash.
The game crashes on the "Good old times" map by BlueByte.
I've got a replay file that shows the last minute before the crash.

The crash happens randomly when I do something with the game objects or when I save the game.
The game also crashes when trying to save the game after the replay finishes.
Here is a screencast on Youtube:

[s25client crash](http://www.youtube.com/watch?v=tlJGHLUmy4I "s25client crash")

The replay file, the savefile and the map is in this zip archive: [crash_save_replay.zip](https://github.com/Return-To-The-Roots/s25client/files/7428438/crash_save_replay.zip).
Please let me know if I can somehow improve the bug report.

Thanks :)

### PR DESCRIPTION
**Pull request by Flamefire**
See https://github.com/Return-To-The-Roots/s25client/issues/1449 and help a bit for https://github.com/Return-To-The-Roots/s25client/issues/1435

Fixes #1449

### CODE REVIEW

**Comment by Flamefire** [comment]
IMO this is not possible. You can only connect to servers with the same version, so the protocol version is the same as the game version. IIRC we don't have a protocol version, do we?
If somehow an old and new client/server communicate with this it will either result in ignoring the version (->all fine) or a runtime error leading in a close of the connection (->also fine) but as mentioned above: As this is after the part where the server information is already exchanged (i.e. the version) and you cannot connect to another version this should never happen anyway

**Comment by Flow86** [comment]
but what if the client is connecting to an old version, thats what the message is for? then that server does not respond with the string.
I think we have something like this, but its only for LobbyProtocol I think

**Comment by Flow86** [comment]
the revision was also never the check criteria at least for the stable versions.

**Comment by Flamefire** [comment]
It was. After the connection was created: https://github.com/Return-To-The-Roots/s25client/blob/master/libs/s25main/network/GameServer.cpp#L918-L919

**Pull request merged**
