### PR TITLE
Remove git-lfs

### LINKED ISSUE #1201: can't start 25client binary anymore with recent git-lfs changes
```
~/s25client/build/bin $ LANG=C ./s25client 
Return To The Roots v20200407-b184727193bcdfb08f81db96125d6f5d057377e9
Compiled with GNU C++ version 9.2.0 for linux 64 Bit

Starting in /home/tim/s25client/build
Searching for drivers in /home/tim/s25client/build/lib64/driver/video
2 video drivers found!
Loaded video driver "(SDL2) OpenGL via SDL2-Library"
OpenGL 4.6 supported
Searching for drivers in /home/tim/s25client/build/lib64/driver/audio
1 audio drivers found!
Loaded audio driver "(SDL) Audio via SDL_mixer-Library"

Starting the game
Loading "/home/tim/s25client/build/share/s25rttr/RTTR/splash.bmp": done in 1ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PAL5.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PAL6.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PAL7.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PALETTI0.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PALETTI1.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PALETTI8.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/RTTR/COLORS.ACT": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/RTTR/LSTS/fonts.LST": failed: File had the wrong header. Possibly wrong file format


ERROR: Some files failed to load.
Please ensure that the Settlers 2 Gold-Edition is installed 
in the same directory as Return to the Roots.
Clearing textures: Finished in 0ms
```

### LINKED ISSUE #1204: Remove usage of git lfs
git-lfs is hard to use (requires setup commands, additional packages, ...), see https://github.com/Return-To-The-Roots/s25client/issues/1201 

Additionally it also has a quota which seems to be low, see https://github.com/Return-To-The-Roots/s25client/pull/1187#issuecomment-612609665

I hence propose we remove git-lfs.

What we needed it for:
- pre-compiled binaries (especially MSVC)
- big LSTs

My proposal to resolve:
- Add a separate repo with pre-compiled binaries that we currently have in the repo. We can clear and reuse the rttr-contrib folder (IMO we don't need what currently is in there). This keeps this stuff optional
- Add a rttr-data repo for lsts and potentially other big files and include as submodule.   
  Got to check what to move there. The whole data folder isn't good as e.g. RTTR/gameData (scripts) should be in the main repo. But LSTs and MAPs should go. Maybe 2 repos? Having an own repo for maps seems to be a good idea.

@Flow86

### PR DESCRIPTION
**Pull request by Flamefire**
- Move files out of git-lfs
- Add contrib binaries via submodule
- Add maps via submodule
- Update turtle (has now CMake support)

@Flow86 Probably better to first migrate the 2 new repos to rttr. I'll update this PR once done

Fixes #1201 
Closes #1204

### CODE REVIEW

**Comment by Flow86** [comment]
so what repositories you need?

s25data and s25maps ?

**Comment by stefson** [comment]
please ping me if this is ready to land, for giving it a test run.

**Comment by Flamefire** [comment]
@Flow86 https://github.com/Flamefire/rttr-devtools and https://github.com/Flamefire/rttr-maps

I invited you there to get access so you can transfer them directly. I don't seem to have the organization rights to do that.

**Comment by Flow86** [comment]
ah you didn't move them with history. I will try to extract them with history

**Comment by Flamefire** [comment]
> ah you didn't move them with history. I will try to extract them with history

Sorry? Do we need the history of the maps?   
For the devtools I'd certainly not use the history because it used to be (mainly) a 7z/rar archive which I now extracted to keep the diffs readable and the changes lower/smaller

So IMO we can use them as-is which also helps keeing the repo size down (it's binary data after all which git isn't good to handle with)

**Comment by Flow86** [comment]
okay I pushed it to:
https://github.com/Return-To-The-Roots/maps
https://github.com/Return-To-The-Roots/devtools

**Comment by Flamefire** [comment]
You didn't like the `rttr-` prefix? Wanted to keep the names unique as maps and devtools are very generic. This will matter when people clone these repos and especially the maps repo is meant to be cloned. Also when doing a standard checkout the folder name will be easier to recognize.

**Comment by Flow86** [comment]
yea its already inside the Return To The Roots namespace. if you fork, you can rename it in github as you like, on your disk you can rename it also

**Comment by Flamefire** [comment]
Hm, that requires extra steps. Git is already hard to use for newcomers.   
Did a quick test if it was even possible to fork if one already has one named like that: It appends a number: https://github.com/Flamefire/maps-1

IMO user experience is better with the prefix. Sure you want to keep it as is?

**Comment by Flow86** [comment]
then we'll go with s25maps, but I would keep devtools

**Comment by Flamefire** [comment]
Fine with that. Users shouldn't need to fork that.

**Pull request merged**
