### PR TITLE
Update player inventory with reserve soldiers used on ClearResources

### LINKED ISSUE #1253: Inventory and Headquarters Number of Private don't match
Hello,
I found out, that the number of privates in the inventory is X+1 to the number in the Headquarters
image
Best regards, Unterwald

### PR DESCRIPTION
**Pull request by Flamefire**
Also don't touch claimed reserve soldiers
Fixes #1253

### CODE REVIEW

**Comment by Flow86** [comment]
tests/s25Main/lua/testLua.cpp:404:9: warning: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto]

**Comment by Flamefire** [comment]
All fixed. Introduced an EnumRange class which we could use in other places as well

**Comment by Flow86** [comment]
is it used anywhere?

**Comment by Flamefire** [comment]
https://github.com/Return-To-The-Roots/s25client/pull/1256/commits/fe6fad34d12e91aa20de41b1a87965deeda8cb30#diff-00158b2a2186cca60bcac43eb001d496R405

**Comment by Flow86** [comment]
ah okay. thought its used somewhere in the code, not only in the unittests :-D yes its a nice idea

**Comment by Flamefire** [comment]
So ready to merge?

**Comment by Flamefire** [comment]
@Flow86 *ping*

**Pull request merged**
