### PR TITLE
Enable more warnings & Cleanup

### PR DESCRIPTION
**Pull request by Flamefire**
- Enable many warnings to find issues and fix those
- Cleanup fix clang-tidy (including modernization like range-based for etc)
- Remove unused headers (especially after switch to C++11)
- Safety via `unique_ptr`s
- Add clang-tidy to travis CI (in 2 steps as all in one takes to long)

Bugs found: Wrong define for OpenGL code used, some shadowing issues, possible leaks or NULL-refs

Also some cleanups via clang-tidy. Goal is that clang-tidy does not find anything which prevents possible bugs or performance issues.

### CODE REVIEW

**Comment by Flow86** [comment]
and:

> [  8%] Building C object external/s-c/resample-1.8.1/src/CMakeFiles/s-c_resample.dir/sndlibextra.c.obj
> <command-line>:0:14: error: "_WIN32_WINNT_WINXP" is not defined, evaluates to 0 [-Werror=undef]

**Comment by Flamefire** [comment]
Jep I'm on it. GCC 8 has more warnings enabled that I missed.

**Comment by Flamefire** [comment]
Biggest cleanup and modernization since ever finished :)

**Comment by stefson** [comment]
The compile is working for clang-7 and gcc-8.2.0, but there is a segfault at runtime: 

```
(gdb) run
Starting program: /usr/bin/s25client 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Return To The Roots v20190412-a684d74fca0457e24a96a9f79c7fc71da270aaad
Compiled with GNU C++ version 8.2.0 for linux 64 Bit

Starting in /usr


WARNING: Your application version has changed - please recheck your settings!

Suche nach Treibern in /usr/lib64/s25rttr/video
2 video drivers found!

Program received signal SIGSEGV, Segmentation fault.
0x000055555561eee3 in VideoDriverWrapper::LoadDriver (this=0x555555b12190, 
    existingDriver=existingDriver@entry=0x0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:67
67	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x000055555561eee3 in VideoDriverWrapper::LoadDriver (this=0x555555b12190, existingDriver=existingDriver@entry=0x0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:67
#1  0x00005555555ceb12 in GameManager::Start (this=0x555555b0ff00)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:67
#2  0x00005555555bdcea in (anonymous namespace)::InitGame () at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:67
#3  0x00005555555becc4 in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:375
#4  0x00005555555bf10c in main (argc=1, argv=0x7fffffffdd18) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440

```

**Comment by Flamefire** [comment]
Damn. Some missing test coverage then. Fixing...

**Comment by stefson** [comment]
starting the game now works for me with both gcc-8 and clang-7, but the pullrequest introduced some tearing it seems: 
2019-04-13-214323_1680x1050_scrot

**Comment by Flamefire** [comment]
Identified the issue: A typo in the texture packing algo. I'm trying to add tests for it...

**Comment by stefson** [comment]
seems to be ok at first glance, but the thumbnails of the maps are still a bit off: 

thumbnails

more evidence: [screenshots.zip](https://github.com/Return-To-The-Roots/s25client/files/3089541/screenshots.zip)

**Comment by Flamefire** [comment]
Do you have a comparison with how it should look like?

**Comment by stefson** [comment]
yes, it's all in the zip

**Comment by Flamefire** [comment]
Thanks. Done in https://github.com/Return-To-The-Roots/s25client/pull/1052/commits/76e9ac2e6b32c5a5f64d55ad8ca46750ff18526e

**Comment by stefson** [comment]
I think this requires some extensive testing: 

some colours are off

This is my enemy - the colour should be yellow, but all workers are in blue (my colour), unless they do one of these randoom tasks or are working as builders/plotters. Idle builder seems to be blue too. Not really sure about the texture of the building which I marked?

**Comment by Flamefire** [comment]
Ok found. Was a C&P bug in libsiedler2. Added a couple tests and fixed this and another issue.

This is actually good. So much is touched that missing important test coverage becomes visible.

**Comment by Flamefire** [comment]
Looks like this is ready to go. @Flow86 and @stefson please give it a quick check. I already did (with and without optimized textures) and it seems to be working in all areas.

BTW: I think we should move the `Point<T>` and `Rect` classes to libutil and use them in libsiedler2. This reduces the amount of parameters (example: `print(buffer, palette, fromX, fromY, toX, toY, toW, toH, playerClr)`) and bugs (the color bug above was a `foo(a.x+b.y, a.y+b.y)` typo)

But in the next PR. We should get this in ASAP before it gets even bigger ;) But most code is nice and modern C++ now :)

**Comment by stefson** [comment]
I don't see any more regressions at the moment.

**Comment by Flamefire** [comment]
@Flow86  Ping

**Comment by stefson** [comment]
I don't want to push anyone, but gcc-8.2.0 replaced by gcc-8.3.0 by now and gcc-9.1.0 hit the repos on my distro. So, can we merge this?

**Comment by Flamefire** [comment]
Still an issue with libsiedler2 with MSVC. Enabling `RTTR_EXTERNAL_BUILD_TESTING` and fixing this now (waiting for build of libsiedler2 on appveyor)

**Comment by Flamefire** [comment]
@Flow86 Done

**Pull request merged**
