### PR TITLE
Lua case sensitive

### LINKED ISSUE #1636: path and filenames for lua files are case sensitive
both folders have to be created/installed with capital letters only: 

```
/usr/share/s25rttr/RTTR/CAMPAIGNS/roman/
/usr/share/s25rttr/RTTR/CAMPAIGNS/world/
```
for the indivual campaign files, all these files have to be renamed to .lua instead of .LUA: 

```
MISS200.lua  MISS202.lua  MISS204.lua  MISS206.lua  MISS208.lua  campaign.lua
MISS201.lua  MISS203.lua  MISS205.lua  MISS207.lua  MISS209.lua
```

likewise for the WORLD folder

### PR DESCRIPTION
**Pull request by ottml**
Fixes  #1636

### CODE REVIEW

**Review by Flamefire — APPROVED** [review]
LGTM. Ready to merge?

**Comment by ottml** [comment]
Yes it's ready. But i was not able to test it on linux because on my vm i does not start due to opengl problems. If you have a linux system on hand @Flamefire can you test it there? Otherwise it can be merged.

**Comment by ottml** [comment]
I tested it on linux too. It's working.

**Comment by stefson** [comment]
@ottml you can ping me if you need a compile test, I've got full linux x86_64 box with gcc and clang. that being said, I checked out your branch and with the latest changes, it's compiling and the bug is fixed!

**Pull request merged**
