### PR TITLE
Use new docker images

### PR DESCRIPTION
**Pull request by Flamefire**

### CODE REVIEW

**Comment by Flow86** [comment]
please rebase PR from s25client/new_docker

**Comment by Flow86** [comment]
there's still a problem with boost detection. The new libraries are named xxx-mt-s but it always tries to add a compiler prefix, which is "" but always gets auto created by FindBoost.cmake because an empty var is a "false". what a mess

**Comment by Flow86** [comment]
see 253a590

**Comment by Flamefire** [comment]
> The new libraries are named xxx-mt-s 

The -s suffix is from static runtime. Did you really build them with static runtime?

**Comment by Flow86** [comment]
yea I fixed that now in the boost library build, so the toolset-tag is there (it was missing before)
they changed the library naming when doing a "tagged" install with version 1.69 ... (...)

The build works now too by adding /usr/.../include to implicit include directories ca9ba6be

**Comment by Flow86** [comment]
follow up #996

**Pull request closed without merging**
