### PR TITLE
Cleaned up new maps folder

### PR DESCRIPTION
**Pull request by Spikeone**
Following maps have been moved, touched, removed:
RTTR/MAPS/NEW/AM_FLUCHTWEG.SWD
- random map
- bad map layout

RTTR/MAPS/NEW/AM_KAESETOAST.SWD
- random map
- bad map layout

RTTR/MAPS/NEW/AM_TALDERSATYRE.SWD
- random map
- bad map layout

RTTR/MAPS/NEW/Gltschrg.swd
- bad textures
- bad object placement
- bad map layout

RTTR/MAPS/NEW/Kreisel.swd
- bad map layout
- bad size for player count
- bad heights
- waterborder because old editor has been used

RTTR/MAPS/NEW/LostWorlds.swd
- bad map layout
- bad object placement

RTTR/MAPS/NEW/Paradise.swd
- bad textures
- bad object placement
- bad heights

RTTR/MAPS/NEW/Random01.swd
RTTR/MAPS/NEW/Random02.swd
RTTR/MAPS/NEW/Random03.swd
RTTR/MAPS/NEW/Random04.swd
RTTR/MAPS/NEW/Random05.swd
RTTR/MAPS/NEW/Random06.swd
RTTR/MAPS/NEW/Random07.swd
RTTR/MAPS/NEW/Random08.swd
RTTR/MAPS/NEW/Random09.swd
RTTR/MAPS/NEW/Random10.swd
RTTR/MAPS/NEW/Random11.swd
- random map
- bad map layout

RTTR/MAPS/NEW/Suedameri.SWD
- bad map layout
- bad texture design
- bad animal placement

RTTR/MAPS/NEW/Toteecke.swd
- bad texture design
- bad heights
- waterborder because old editor has been used
- bad object design

RTTR/MAPS/NEW/pangea.wld
- could not pass some paths

RTTR/MAPS/NEW/3islands.wld → RTTR/MAPS/OTHER/3islands.wld
- bad maplayout which is not balanced for multiplayer

RTTR/MAPS/NEW/4ZIGARRE.SWD → RTTR/MAPS/OTHER/4ZIGARRE.SWD
- bad maplayout which is not balanced for multiplayer

RTTR/MAPS/NEW/AM_FANGDERZEIT.SWD → RTTR/MAPS/OTHER/AM_FANGDERZEIT.SWD
- random map
- maplayout is not balanced for multiplayer

RTTR/MAPS/NEW/Bergruft.swd → RTTR/MAPS/OTHER/Bergruft.swd
- bad texture design
- waterborder because old editor has been used
- bad height design

RTTR/MAPS/NEW/Bergschlumpf.swd → RTTR/MAPS/OTHER/Bergschlumpf.swd
- maplayout is not balanced for multiplayer
- textures need improvement

RTTR/MAPS/NEW/DerSalzsee.swd → RTTR/MAPS/OTHER/DerSalzsee.swd
- no heights
- missing objects

RTTR/MAPS/NEW/Ecuador.SWD → RTTR/MAPS/OTHER/Ecuador.SWD
- bad texture design
- maplayout is not balanced for multiplayer

RTTR/MAPS/NEW/Gluecksklee.swd → RTTR/MAPS/OTHER/Gluecksklee.swd
- map is not balanced for multiplayer

RTTR/MAPS/NEW/OwnLands.swd → RTTR/MAPS/OTHER/OwnLands.swd
- needs better textures
- needs better heights
- needs better objects

RTTR/MAPS/NEW/bigslaugh2.swd → RTTR/MAPS/OTHER/bigslaugh2.swd
- needs better heights
- needs better textures
- needs animals

RTTR/MAPS/NEW/dv016rmp.swd → RTTR/MAPS/OTHER/dv016rmp.swd
- singleplayermap

RTTR/MAPS/NEW/dv102rmp.swd → RTTR/MAPS/OTHER/dv102rmp.swd
- singleplayermap

### CODE REVIEW

**Comment by Spikeone** [comment]
Hopefully I did better this time ;)

**Comment by Flamefire** [comment]
Yes you did. But you broke my tests: `Bergruft.swd` was used in the test code to check loading etc. Can you look for the path in `src/test` and change it so it matches the new location?

**Comment by Flamefire** [comment]
Oh and can you comment on each removed map WHY it was removed? This is good for at least documentation purposes and we can direct people to this PR if there are any questions. So add this to the initial description. Also I want to know the reasons. E.g. Totecke was at least interesting. 

And I know you just moved those, but can you rename maps like `dv102rmp.swd` to appropriate names? Filename should normally match the map name.

**Comment by Flamefire** [comment]
>  just need to find out how to change a commit message.

`git commit --amend` changes the last commit. But I think it is enough if you edit your PR description here as this message might get to long.

> as those might contain spaces which is not supported by the original game.

Usual way to handle this: Replace spaces by underscores. see `AM_FLUCHTWEG.SWD`. But see below

> But if you insist Mapname = Filename

Not really. I just would like to have *some* relation between map name and file name. I was confused about `dv016rmp.swd`. What map is this?   
This should rather be `demo_v016_rmp.swd` or so, although I find even that name strange.

The rest should be fine. They don't need to match exactly, just so that when you have either name you can find the other. E.g. "Der Salzsee" might have a filename of "Salzsee.swd" but "sase.swd" would be bad.

**Comment by Spikeone** [comment]
Yeah, you are right, should use _, sadly the editor doesn't support long filenames had to change names of some files for inspecting them...

How about first 8 letters of the mapname? Should suffice to find the correct file... But that might bring problems as well (der grosse berg or der grosse see would both result in der_gross). 
I'd really like to keep it simple enough one can just paste files into the worlds folder and edit them - but that might not be possible. On the other hand we could use the filename rather than map name in rttr to have longer names.

**Comment by Flamefire** [comment]
Thats's why I suggested removing the article "der". But well it doesn't really matter. Only things worth changing would be those "demo" maps (whatever they are) because their names are confusing. So change those and spare the time for the rest.

**Comment by Spikeone** [comment]
Mh, I see a failing test but have no idea why :-/

**Comment by Flamefire** [comment]
Just change the path to the new path but use the same map. This will be the easiest

**Comment by Spikeone** [comment]
Thats right, but the test shouldn't fail here anyway:

> CalcChecksumOfFile(testMapPath) == CalcChecksumOfFile(outMap.filePath) has failed [10716 != 10616]

Not regarding which map is used or am I wrong? I mean just in case I decide to change that map quite a lot or replace it by an other version or whatever, the test should work with an other map, shouldn't it?

Thats at least the reason why I'd like to get it running with TueranTuer (and I kept that map as it is perfect for a lot of testing ;))

**Comment by Flamefire** [comment]
You are right. This test checks that load+save of a map does not change it. Seems we are missing something there. Maybe the map has some unused stuff set to different values? You can put a Breakpoint on that line and compare the maps manually.

**Comment by Spikeone** [comment]
Oh boy, here we go again beloved cmake and contrib folder.

Well need a working build anyway as I'd like to create some addons

**Comment by Flamefire** [comment]
It should be quite easy now. The CMake files, Readme and wiki have been improved a lot, check them and report all new problems and solutions.

**Comment by Flamefire** [comment]
@Spikeone Want to complete this?

**Comment by Spikeone** [comment]
@Flamefire Want to yes... gotta find out why the test fails with another map - I'll put it on my list for the end of this week :)

**Comment by Spikeone** [comment]
@Flamefire sadly I get this weird error when building:
```
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\shlobj.h(1054): error C2220: Warnung wird als Fehler interpretiert, es wurde keine object-Datei generiert.
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\shlobj.h(1054): warning C4091: "typedef ": Ignoriert auf der linken Seite von "tagGPFIDL_FLAGS", wenn keine Variable deklariert wurde
```

any Ideas? I reread your PM regarding this and installed those packages for vs2017, yet no luck

**Comment by Flamefire** [comment]
Can't remember what that was. Can post the whole log or at least the full trace to a rttr file

**Comment by Spikeone** [comment]
well, for building audiodrv the output is:
```
1>------ Erstellen gestartet: Projekt: s25util_common, Konfiguration: Debug Win32 ------
1>System_Win32.cpp
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\shlobj.h(1054): error C2220: Warnung wird als Fehler interpretiert, es wurde keine object-Datei generiert.
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\shlobj.h(1054): warning C4091: "typedef ": Ignoriert auf der linken Seite von "tagGPFIDL_FLAGS", wenn keine Variable deklariert wurde
1>Die Erstellung des Projekts "s25util_common.vcxproj" ist abgeschlossen -- FEHLER.
========== Erstellen: 0 erfolgreich, 1 fehlerhaft, 6 aktuell, 0 übersprungen ==========
```

**Comment by Spikeone** [comment]
Lets see if I can get this working :)

**Comment by Flow86** [comment]
@Flamefire  is this outdated?

**Comment by Flamefire** [comment]
Yes: Done in https://github.com/Return-To-The-Roots/s25client/pull/1489

**Pull request closed without merging**
