### PR TITLE
improve addon description

### PR DESCRIPTION
**Pull request by Xermio**

### CODE REVIEW

**Comment by Flamefire** [comment]
@Spikeone What do you say? LGTM

**Comment by Spikeone** [comment]
@Flamefire Well, I'm not sure at all. Is it really true, that "blocked by stone" is taken into account? I hope this is not the case as stones are often meant as temporary barrier...
If the description is correct, I'd ask for an addon change, if the description is wronge, I'd ask to change the description ;)

On second thought, stone might not be granite as this is what quarrys mine - still this could confuse people like I was :confused:

**Comment by Flamefire** [comment]
Checked the implementation: Only terrain is checked, no objects. @Xermio Could you update the description please?

**Comment by Shawn8901** [comment]
Yeah Stone is not included. We discussed it already when i submitted the PR, that objects like stone/wood should not be checked.
So it should be updated to something like `(Path blocked by terrain like sea, lava, etc.)`?

**Comment by Xermio** [comment]
True, stone does really not count as blocking. Updated the description, please check again.

**Comment by Spikeone** [comment]
Are static object taken into account? For example ruins? Are LUA spawned objects taken into account? One should then add "static objects" or something like that, but with the current description I'm also okay :)

**Comment by Flamefire** [comment]
Nope they are not.

**Pull request merged**
