### PR TITLE
Add new map

### PR DESCRIPTION
**Pull request by Xermio**
Selfmade map called "Neighbourhood".

8 player, but playable with less too of course.
Also nice to play with 3 players vs 5 AIs.

### CODE REVIEW

**Comment by Spikeone** [comment]
Damn, how can I download the map to check it? :x

**Comment by Xermio** [comment]
Should be downloadable within the commit. @Spikeone 

https://github.com/Return-To-The-Roots/s25client/blob/62bed02610ea40476d8922b22c1403b28dbe35d4/RTTR/MAPS/NEW/Neighbourhood.SWD

**Comment by Flow86** [comment]
@Spikeone 
use "Files changed" and then "View" on the file. There you can download it.

**Comment by Xermio** [comment]
The simple map design was by intention. But I can make a "improved" public version.

I personally like flat terrains and don't need "visual objects". :)

**Comment by Spikeone** [comment]
Hm - what about we put those map into "other" then? we should also clean up the other maps folder as well.

**Comment by Spikeone** [comment]
https://drive.google.com/open?id=1K7WGWJRk4-jSHAXZDc1OspXT8aCxsagq this one is a slightly better version. Although I still propose adding this map to the "other" folder and cleaning up all maps so the "new" (RttR) folder contains all multiplayer maps which are good and other contains singpleplayer maps or lower quality multiplayer maps. There is nothing more frustrating than playing a map for the first time and realizing that one player just can't win at all.

**Comment by Xermio** [comment]
Moved the map to the "OTHER" folder. Merge it as is or not.

**Pull request merged**
