### PR TITLE
Enhance CI: Update compilers and tested standards

### PR DESCRIPTION
**Pull request by Flamefire**

### CODE REVIEW

**Comment by Flamefire** [comment]
@Flow86 All done, but it seems the required tests must be adjusted. Maybe only make the ones with the minimal compiler versions required, so we can easily update the others

**Comment by Flow86** [comment]
okay which ones do you want to be required?

**Comment by Flamefire** [comment]
> okay which ones do you want to be required?

Static analysis, gcc-6, clang-7 (2 each), clang-macos, jenkins
All others should pass but I don't think we have to enforce this as those with merge rights know not to merge when any fails. Appveyor should also be required but is sometimes flaky, so manual inspection and ignoring that is ok

**Comment by Flow86** [comment]
ok. new list will be
grafik
then?

**Comment by Flamefire** [comment]
Looks good, yes

**Review by Flow86 — APPROVED** [review]

**Pull request merged**
