### PR TITLE
Jenkins CI: Increase timeout for Apple build

### PR DESCRIPTION
**Pull request by Flamefire**
2hrs doesn't seem to be enough on OSX.

### CODE REVIEW

**Comment by Flow86** [comment]
the 120 should be enough - the problem is that since an update sometimes the jenkins agent containers do not spin up correctly and time out

**Comment by Flamefire** [comment]
What do you mean by "do not spin up correctly"? I checked one such timed-out job and have seen that it started building most of the stuff on OSX but at some point stopped (killed by the timeout)

**Comment by Flow86** [comment]
ah okay then it was one of those where the docker container got stopped in the background and did not notice that he lost its container and timed out

**Comment by Flamefire** [comment]
Not sure I understood that. So the timeout doesn't need to be raised? If so please close this PR.

And the required macos GHA check still needs updating

**Pull request closed without merging**
