### PR TITLE
Add textures

### LINKED ISSUE #37: Missing original textures
There are some original textures missing at the moment - for example buildable water, no ship water, buildable desert, buildable mountain. Although they were not available in the original editor some textures were used - for example buildable water - which still causes problems in rttr.

Please refer: http://settlers2.net/documentation/world-map-file-format-wldswd/

### PR DESCRIPTION
**Pull request by Flamefire**
Fixes #37

### CODE REVIEW

**Comment by Flamefire** [comment]
@jhkl Please check the AI changes.
Can anyone get Merri to look over the new lava texture animation? Orientation seems to be off...

**Comment by Flamefire** [comment]
@Spikeone or @MarcusSt Any chance you can figure out, how the new lava textures should be drawn and how they should be extracted? They are similar to normal lava/water but e.g. are smaller. Check https://github.com/Flamefire/s25client/commit/6cdd9f37be6a24e9a83981ac6dec3d870686b9c3 for the TODOs. I tried "Flow of Lava" (http://settlers2.net/the-settlers-2/texture-set-new-greenland/) but it doesn't look right.

**Comment by Spikeone** [comment]
I don't know exactly what you mean but: those work like water textures, means they are no 'normal' square as buildable textures but water. Also the actual movement was achieved by palette rotation just like normal lava (or maybe reverted?). You may use the paletti03.lbm of some versions to check the original behavior - but I'm not 100% that this file was included with extra textures in all versions.

**Comment by Flow86** [comment]
in the old code, extractanimatedtexture had some additional parameters for lava exactly for that

**Comment by Flamefire** [comment]
@Spikeone There are 2 important things:   
1) Extract animated texture from LBM with startcolor and numAnimations (See https://github.com/Flamefire/s25client/commit/6cdd9f37be6a24e9a83981ac6dec3d870686b9c3#diff-51a8064f6fc6cee95b3037599f3d1c20R1014) but there I'm not sure, if the startColor and animCount is right (In TerrainData.cpp i just used the same values as for normal lava)   
2) Drawing: Only a part of the extracted texture is drawn. (See https://github.com/Flamefire/s25client/commit/6cdd9f37be6a24e9a83981ac6dec3d870686b9c3#diff-49ab5d3555baf7d25a20786145f23405R310) I'd need to know which part it is for the small lava stuff

@Flow86 Can you point me to that code? How did you got that? By reverse engineering the original?

**Comment by Spikeone** [comment]
Sadly I have no idea, I can only tell you that the moved lava texture is smaller than normal textures and may already be the "small drawn part". My initial report was about having buildable water, mountains and desert as this rambles certain cool map designs.
Most lava textures have been tested by merri

**Comment by Flamefire** [comment]
Well at least I added buildable water and buildable mountain. The lava can be considered alpha ;)
What do you mean by desert? There are 2 desert types that are actually equal AFAIK

**Comment by Flamefire** [comment]
I guess I fixed all issues. Can anyone (best would be @jhkl ) look over a56d7f2 to make sure all properties are correctly reflected in AI etc.? Then this can be merged

**Comment by jhkl** [comment]
I just downloaded & compiled your branch (f0fb96545e2f82e44b17050c2cca7ef190ca4c3e
). After loading a replay, it went async after ~100 GF. Is it intended by any of your commits to change anything that might lead to a different behaviour?

The replay was running fine a couple of days ago with the master branch, I did not check again today. There might be changes that caused this.

Link to replay: https://dl.dropboxusercontent.com/u/1589203/rttr/2015-08-09_17-30-41.rpl

I think I won't really have the time to review ~1500 changed lines in the near future in detail. Anyone else...?

**Comment by Flamefire** [comment]
@jhkl Yes this async is expected. There was a bug where t1 was checked 2 times instead of checking t1 and t2 and the AI checks where not complete (it did not check for all forbidden/allowed terrain types) One of the reasons why I unified the handling...

**Comment by Flamefire** [comment]
Ok I just checked your replay again. Only asyncs are caused by nofAnimal which is expected. Reverting that fixed the asyncs. However animals can also use mountain_meadow so I added another function for that.

**Comment by Flamefire** [comment]
@jhkl And about the changed line count; Only important commit is a56d7f2. There most of the lines account to the new TerrainData file and the moved structs. Only thing to really review are the AI changes which are much less and best done by you as I guess you have the best understanding. Besides that: I was able to run your replay to ~50k GFs without async (after temporarly reverting the nofAnimal changes which cause expected asyncs) so if you can just scan over the Ai changes I'd merge it. @Spikeone is waiting for this ;)

**Comment by jhkl** [comment]
> Yes this async is expected. There was a bug where t1 was checked 2 times instead of checking t1 and t2 (noAnimal)...
Ok!

> ... and the AI checks where not complete (it did not check for all forbidden/allowed terrain types) One of the reasons why I unified the handling...
It is a replay. There is no AI activity.

> Err... Wouldn't std::random_shuffle(potentialTargets.begin() + hq_or_harbor_without_soldiers, potentialTargets.end()); in the AI also cause an async replay?
No. The AI is only executed at the hosting player, so no need for synchronized randomness. Actually, addding the synchronized random generator in the AI code would instantly create asyncs.


> @jhkl And about the changed line count; Only important commit is a56d7f2. There most of the lines account to the new TerrainData file and the moved structs. Only thing to really review are the AI changes which are much less and best done by you as I guess you have the best understanding.
Ok, I looked over the AI* files of a56d7f2. Looks fine. I hope I did not write that ugly copy&paste stuff. :)

**Comment by Flamefire** [comment]
Alright. Then all seems to be ok as the asyncs were removed by removing the animal change.

If no one has objections till tomorrow I'll merge that.

**Pull request merged**
