### PR TITLE
Remove SDL1 in favor of SDL2

### LINKED ISSUE #1208: build fails: unused parameter 'x' [-Werror,-Wunused-parameter]
I'm trying to build todays version according to readme instructions on `OSX 10.15.4` and get the following error from boost:
```
cmake -DCMAKE_BUILD_TYPE=Release ..
make
...
[ 97%] Building CXX object tests/s25Main/UI/CMakeFiles/Test_UI.dir/main.cpp.o
In file included from /Users/daniel/Documents/Coding/CPP/s25client/tests/s25Main/network/testLobby.cpp:25:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/mock.hpp:13:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/object.hpp:13:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/detail/root.hpp:17:
/Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/detail/mutex.hpp:106:36: error: 
      unused parameter 'x' [-Werror,-Wunused-parameter]
        lock( BOOST_RV_REF( lock ) x )
                                   ^
/Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/detail/mutex.hpp:108:47: error: 
      unused parameter 'x' [-Werror,-Wunused-parameter]
        lock& operator=( BOOST_RV_REF( lock ) x )
                                              ^
In file included from /Users/daniel/Documents/Coding/CPP/s25client/tests/s25Main/network/testLobby.cpp:25:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/mock.hpp:14:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/reset.hpp:15:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/detail/functor.hpp:13:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/detail/function.hpp:15:
In file included from /Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/detail/../constraints.hpp:13:
/Users/daniel/Documents/Coding/CPP/s25client/external/turtle/include/turtle/constraint.hpp:226:5: error: 
      'BOOST_MSVC' is not defined, evaluates to 0 [-Werror,-Wundef]
#if BOOST_MSVC
    ^
```

I have boost installed:
```
brew info boost
boost: stable 1.72.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.72.0_1 (14,466 files, 648.5MB) *
  Poured from bottle on 2020-04-13 at 05:49:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb
```

Do I need another boost version? Or is something else missing on my machine?

### PR DESCRIPTION
**Pull request by Flamefire**
Follow-up to #1189 using CMake fixes from there, thanks @chewi

Removes all SDL1 references in rttr and s25edit including the audio

Closes #1208

### CODE REVIEW

**Comment by Flamefire** [comment]
@Flow86 Jenkins shows that SDL_mixer2 wasn't build for 32bit. Remove 32 bit OSX support or install SDL2_mixer with both?

> ld: warning: ignoring file /usr/lib/apple/SDKs/MacOSX10.11.sdk/Library/Frameworks//SDL2_mixer.framework/SDL2_mixer, file was built for x86_64 which is not the architecture being linked (i386): /usr/lib/apple/SDKs/MacOSX10.11.sdk/Library/Frameworks//SDL2_mixer.framework/SDL2_mixer

**Comment by Flow86** [comment]
> 
> 
> @Flow86 Jenkins shows that SDL_mixer2 wasn't build for 32bit. Remove 32 bit OSX support or install SDL2_mixer with both?
> 
> > ld: warning: ignoring file /usr/lib/apple/SDKs/MacOSX10.11.sdk/Library/Frameworks//SDL2_mixer.framework/SDL2_mixer, file was built for x86_64 which is not the architecture being linked (i386): /usr/lib/apple/SDKs/MacOSX10.11.sdk/Library/Frameworks//SDL2_mixer.framework/SDL2_mixer

we could drop 32bit support, since apple itself doesnt support in anymore. but I don't know if someone still has an older mac?

I will look at the SDL2_mixer in the next days and check why its not multi arch

**Comment by Flow86** [comment]
Hmm, I do not build SDL2 for mac by source, it seems the package from libsdl.org does not contain 32bit architecture.

perhaps we should simply drop the 32bit support? @Flamefire what do you think?

**Comment by Flamefire** [comment]
If it's not easily possible to build it for multi arch then yes. Newer sdl2 has cmake so maybe it's easy?

**Comment by Flow86** [comment]
> If it's not easily possible to build it for multi arch then yes. Newer sdl2 has cmake so maybe it's easy?

well, I think there was a reason not doing it. but I can try again

**Comment by Flamefire** [comment]
Well there is a gcc-fat.sh with

```
# Build Universal binaries on Mac OS X, thanks Ryan!
#
# Usage: ./configure CC="sh gcc-fat.sh" && make && rm -rf x86 x64

DEVELOPER="`xcode-select -print-path`/Platforms/MacOSX.platform/Developer"

# Intel 32-bit compiler flags (10.6 runtime compatibility)
GCC_COMPILE_X86="gcc -arch i386 -mmacosx-version-min=10.6 \
-DMAC_OS_X_VERSION_MIN_REQUIRED=1040 \
-I/usr/local/include"

GCC_LINK_X86="-mmacosx-version-min=10.6"

# Intel 64-bit compiler flags (10.6 runtime compatibility)
```
Looks promising at least

**Comment by Flamefire** [comment]
@Flow86 any update on this?

**Comment by Flow86** [comment]
Sorry, I'm still on it. If I'm honest I already forgot it.

**Comment by Flamefire** [comment]
No update yet? I'd suggest we remove 32Bit support and add it back when requests come in. I think you'd be faster removing that than me as probably the website or updater needs to be adapted? Could you do that? Especially the submodule update is blocking other work :)

**Comment by Flamefire** [comment]
@Flow86 To get this done I excluded the x32 build on OSX as suggested above. We can readd it later if the need arises.

**Comment by Flamefire** [comment]
*ping*

**Comment by Flow86** [comment]
I got my old mac running again, and I'm installing xcode at the moment. Hope it doesnt crash again. After that I can try to get the SDL2_mixer working universally

**Comment by Flow86** [comment]
okay. It seems that you even can't build i386 with a current xcode anymore:

"Fatal Error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. "

so I would say, we simply drop the i386 architecture anyhow?

**Comment by Flamefire** [comment]
> so I would say, we simply drop the i386 architecture now?

yep, I already added a commit here that does that.

However I'd get #1205 ready first which avoids the update of the contrib archive here leading to a conflict there

**Comment by stefson** [comment]
I test compiled the branch with clang on linux, the only thing I noticed was that for audio there's still `sdl` listed in the settings menue of the game. Don't know if that's desired behavior. 

Also I'm going to play for a few hours over the weekend, and propably going to test on arm64! :)

**Comment by Flamefire** [comment]
@Flow86 ready to merge

**Pull request merged**
