### PR TITLE
Addon text improvements

### PR DESCRIPTION
**Pull request by Flamefire**
This makes the addon texts translatable and also shortens them a bit. No need for "Allows you to change..." in the tooltips. Lengthy tooltips are hard to read especially as we got many settings.

### CODE REVIEW

**Comment by Flow86** [comment]
you know that they were translated in the addon-table, thats why the gettext_noop was there (so the text parser will find the strings, but that the widgets do not translate them "twice")

**Comment by Flamefire** [comment]
So these strings are translated when they are displayed? Why not translate them here? It is shorter and clearer. We just need to remove the 2nd translation...

**Comment by Flow86** [comment]
I dont know anymore why, but I think there was a reason for that

**Comment by Flamefire** [comment]
Well then if it works like this PR (with the removal of the 2nd translation) I would use this. Cleaner, more consistent and hence easier for new devs

**Comment by Flow86** [comment]
okay

**Pull request merged**
