### PR TITLE
Fix videodrivers

### PR DESCRIPTION
**Pull request by Flamefire**
Follow-up for issues mentioned in #1066

This fixes WinAPI+OpenGL, wrongly selected resolutions and improves usability with SDL (window centred and possibly resized to fit screen)

### CODE REVIEW

**Comment by Flow86** [comment]
what about SDL1 video driver?

**Comment by Flamefire** [comment]
> what about SDL1 video driver?

What do you mean? I'd deprecate SDL1 and WinAPI as we have SDL2 working which is superior. So only bugs are fixed in SDL1/WinAPI but no new features added

**Comment by Flow86** [comment]
so SDL1 does not need fixing?

**Comment by Flamefire** [comment]
I'm not aware of a bug that needs fixing there

**Pull request merged**
