### PR TITLE
Improved hitpoint text

### PR DESCRIPTION
**Pull request by Ribosom**
Removed max hitpoints. Colour of hitpoints will be red if a soldier has not the maximal amount of hitpoints.

### CODE REVIEW

**Comment by Flamefire** [comment]
Just an Idea as you used colors here: What about a color scale? Like green=full HP, orange= more than half HP, red = max half HP

**Comment by Flamefire** [comment]
Can you tell me if you like the color scale idea? If not, I'll merge that as it is right now.

**Comment by Ribosom** [comment]
Sorry had not much time this weekend. I will try the colour scale later. :-)

**Comment by Flamefire** [comment]
Looks good. Thank you!

**Pull request merged**
