### PR TITLE
s25update submodule update: libCURL 7.32+ fix

### PR DESCRIPTION
**Pull request by S4enL0ng**

### CODE REVIEW

**Review by Flamefire — CHANGES_REQUESTED** [review]
The version number checked for is seemingly wrong, see the failure on appveyor:
> `C:\projects\s25client\external\s25update\src\s25update.cpp(199): error C2065: 'CURLOPT_XFERINFOFUNCTION': undeclared identifier`

And my comment in https://github.com/Return-To-The-Roots/s25update/pull/10

**Comment by S4enL0ng** [comment]
Problems should now be fixed. It does work for me.
Tests are passed.

**Review by Flamefire — DISMISSED** [review]

**Comment by S4enL0ng** [comment]
Hmpf... how is this fixable?
```
/home/runner/work/s25client/s25client/external/s25update/src/s25update.cpp:123:15: warning: 'ProgressBarCallback' is a static definition in anonymous namespace; static is redundant here [readability-static-definition-in-anonymous-namespace]
Error: Process completed with exit code 1.
```

```
#if CURL_AT_LEAST_VERSION(7, 32, 00)
static size_t ProgressBarCallback(std::string* data, curl_off_t dltotal, curl_off_t dlnow, curl_off_t /*ultotal*/,
                                  curl_off_t /*ulnow*/)
#else
int ProgressBarCallback(std::string* data, double dltotal, double dlnow, double /*ultotal*/, double /*ulnow*/)
#endif
```

**Comment by Flamefire** [comment]
> I see the problem for readability. but i dont know how i can satisfy this test there.

Just what it tells you: Remove the `static` in `static size_t ProgressBarCallback` as it is redundant because it already is in an anonymous namespace. Missed that too in the other PR as it only is a "readability" issue.

**Comment by S4enL0ng** [comment]
Oh, i thought it meant the doubled definition altogether, not only the static definition.
Okay, thanks.

**Review by S4enL0ng — COMMENTED** [review]
Requested Change is made and can be approved =)

**Review by Flamefire — APPROVED** [review]

**Pull request merged**
