### PR TITLE
Fixes according to static analysis

### PR DESCRIPTION
**Pull request by Flamefire**
Fix all found issues by using PVS Studio.

Mostly shadowing issues which can lead to confusion of members vs parameters but also some safety stuff (boost::array, missing copy operator, possibly throwing dtor, bool to int conversion, ...)
Renaming was done by VisualAssist so should be save (if any error, it would not be able to compile, besides that I'd just trust the refactoring function)

For review:

- [ ] Shading issue: https://github.com/Return-To-The-Roots/s25client/issues/272
- [ ] Safer use of minimap (replace void*)

### CODE REVIEW

**Comment by Flow86** [comment]
you can work around the fPIC stuff if you disable static boost libraries and use the dynamic ones (perhaps we should add some kind of configure check if boost is build with fpic and if not, use dynamic librarys?)

**Comment by Flamefire** [comment]
@Flow86 I'd rather make it an option to use static boost libs: `OPTION(Boost_USE_STATIC_LIBS ON)`
Not sure if an automatic check would work.

**Comment by Flow86** [comment]
yes an automatic check would be possible since you could try to link a dynamic library (with -fpic) and boost which will fail if boost is without fpic

**Comment by stefson** [comment]
I guess s25rttr is broken with system-boost-1.56.0 ; the bug I filled in #276 is not occuring when upgrading to system-boost-1.58.0 

Will do some further investigations tomorrow.

**Pull request closed without merging**
