### PR TITLE
Show instant Victory

### PR DESCRIPTION
**Pull request by Flamefire**

### CODE REVIEW

**Comment by Flamefire** [comment]
@Spikeone Check Code starting at https://github.com/Return-To-The-Roots/s25client/pull/909/commits/60bb788aca604f1c90837e08ff33ef90ab43c640#diff-a828fcc69b4fadf2331e1b11fbe6a6caR1277

What do you think?

**Comment by Spikeone** [comment]
As it will take ages for me to get a build running, it should look that way:
image

**Comment by Flamefire** [comment]
That's why I referred to the code. I think it is simple enough to get an idea what it does. Currently it looks like:

bildschirmfoto vom 2018-11-09 09-27-20

Note how the title changes between victory and defeat and that additionally a log message is shown.

Your idea is also good but that requires #798 and an idea how to scale this to many players (make it simply as wide as the images get?) Also are the colors enough or do we want the player names too?

**Comment by Flamefire** [comment]
Ok, for now I suggest: I create a window similar to the original, but with a list of player names instead of the avatars as we don't have them. The text will either be "The winners" or "The winner". There will be 1 name per line. The message text in the main window should be kept to be consistent with the "player x defeated" text.

You create another issue depending on the avatar issue with your suggestion. Maybe create a mockup how the player names shall be put into the color box. IMO this will be very hard because what color shall the text be? The player colors may be random (in the future) so the text can get unreadable. Also what happens for long(er) names? All this need to be solved but as a separate issue. First we need "something". As we don't have avatars I don't see any other option than a plain list of names

**Comment by Spikeone** [comment]
Agreed, will create an issue with mockup

**Comment by Flamefire** [comment]
@Spikeone *ping*

**Comment by Spikeone** [comment]
Really need to check whats up with my notifications.

@Flamefire _pong_ - please change the "continue game"'s button texture to gray and translate "end game" :)

**Comment by Flamefire** [comment]
Ah yes, forgot that ;)

"End game" is translated (original language is English), the rest is not as it's new.

**Comment by Flamefire** [comment]
New dialogue:

bildschirmfoto vom 2018-11-20 09-36-08

**Comment by baka0815** [comment]
Looks like there is a translation problem as "Continue game" is in English while "Spiel beenden" is in German.

**Pull request merged**
